version: '3.5'
networks:
  plugin-arch-server-net:
    name: plugin-arch-server-net
    external: true

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://otel-collector:9411/api/v2/spans # Zipkin
    networks:
      plugin-arch-server-net:
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"